### ISSUE TITLE
USER STORY: anonymous feedback

### ISSUE THREAD

**Issue by saroltah** [saroltah/love-running#3]
#  User Story: 
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity in my poll response**

# Acceptance criteria
a, The option should be provided by checkbox
b, The checkbox should be checked by default
c, The option should appear next to submit button
d, After submitting the default submission confirmation should be adjusted to include the user name

# Tasks
- [x] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test script
- [ ] Test the functionality
